# Use a base image, for example, a lightweight Linux distribution with Nginx
FROM nginx:alpine

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Copy website files to the default Nginx web root directory
COPY . .

# Expose port 80 for the web server
EXPOSE 80
